apps:
  - name: 'backend'
    script: './src/main.js'
    instances: 'max'
    autorestart: true
    exec_mode: 'cluster'
    watch: false
    max_memory_restart: '500M'
    out_file: './out.log'
    error_file: './error.log'
    merge_logs: true
    ignore_watch:
      - 'node_modules'
      - 'out.log'
      - 'error.log'
    env:
      NODE_ENV: 'production'
